### ISSUE TITLE
Problem compiling metron 

### ISSUE THREAD

**Issue by ztz1989** [tbarbette/fastclick#143] opened 2018-11-15 16:36 UTC
Dear all, I have encountered an issue when compiling the metron branch. During compilation phase, it reports an error like this:

**../lib/librte_parse_17.8.0/testpmd.h:381:13: error: use of enum 'dcb_queue_mapping_mode' without previous declaration**

I'm using DPDK 17.08, and I can compile and run fastclick master branch without any problem. Could you give me some hints about this?

  Best,
  Tianzhu

**Comment by gkatsikas** [comment] 2018-11-16 06:40
Hi,

Could you please try to: make clean && make

There is some magical sed manipulation in the build process, which might have failed.

**Comment by tbarbette** [comment] 2018-11-16 07:20
FYI, this is caused by the fact we import some DPDK parsing code that is not supposed to be.
When you'll have Metron running do not hesitate to come back to us with improvements we could do on the documentation.

**Comment by gkatsikas** [comment] 2018-11-20 14:55
@ztz1989 Did you manage to compile metron?
Please let us know if you still have problems.

**Comment by tbarbette** [comment] 2018-11-22 12:01
Problem should be solved, closing

**Closed by tbarbette** 2018-11-22 12:01 UTC
Labels: metron
